import type { Product } from '@autonomous-commerce-lab/shared';

export const mockProducts: Product[] = [
  {
    id: 'prod-001',
    title: 'Cold Brew Coffee',
    description: 'Smooth coffee concentrate for iced drinks.',
    price: 12.5,
    currency: 'USD',
    status: 'active',
    tags: ['coffee', 'beverage', 'cold'],
    createdAt: '2026-02-12T09:30:00.000Z',
  },
  {
    id: 'prod-002',
    title: 'Espresso Beans',
    description: 'Dark roast whole beans for espresso shots.',
    price: 15.99,
    currency: 'USD',
    status: 'active',
    tags: ['coffee', 'beans', 'espresso'],
    createdAt: '2026-02-11T10:20:00.000Z',
  },
  {
    id: 'prod-003',
    title: 'Ceramic Mug',
    description: 'Matte ceramic mug with 350ml capacity.',
    price: 9.99,
    currency: 'USD',
    status: 'active',
    tags: ['mug', 'kitchen', 'drinkware'],
    createdAt: '2026-02-10T08:00:00.000Z',
  },
  {
    id: 'prod-004',
    title: 'Reusable Bottle',
    description: 'Insulated bottle that keeps drinks cold for 24 hours.',
    price: 19.49,
    currency: 'USD',
    status: 'draft',
    tags: ['bottle', 'outdoor', 'drinkware'],
    createdAt: '2026-02-09T14:10:00.000Z',
  },
  {
    id: 'prod-005',
    title: 'Oat Milk',
    description: 'Barista blend oat milk for coffee drinks.',
    price: 4.25,
    currency: 'USD',
    status: 'active',
    tags: ['milk', 'vegan', 'coffee'],
    createdAt: '2026-02-08T07:40:00.000Z',
  },
  {
    id: 'prod-006',
    title: 'Vanilla Syrup',
    description: 'Sweet vanilla syrup for cafe-style beverages.',
    price: 6.75,
    currency: 'USD',
    status: 'draft',
    tags: ['syrup', 'flavor', 'coffee'],
    createdAt: '2026-02-07T16:55:00.000Z',
  },
  {
    id: 'prod-007',
    title: 'Chocolate Cookies',
    description: 'Crunchy chocolate cookies for snack pairing.',
    price: 5.5,
    currency: 'USD',
    status: 'archived',
    tags: ['snack', 'bakery', 'chocolate'],
    createdAt: '2026-02-06T11:05:00.000Z',
  },
  {
    id: 'prod-008',
    title: 'Matcha Powder',
    description: 'Premium ceremonial grade matcha powder.',
    price: 21,
    currency: 'USD',
    status: 'active',
    tags: ['tea', 'matcha', 'beverage'],
    createdAt: '2026-02-05T12:30:00.000Z',
  },
  {
    id: 'prod-009',
    title: 'Paper Cups',
    description: 'Recyclable takeaway paper cups pack of 50.',
    price: 8,
    currency: 'USD',
    status: 'archived',
    tags: ['cups', 'takeaway', 'supplies'],
    createdAt: '2026-02-04T09:15:00.000Z',
  },
  {
    id: 'prod-010',
    title: 'Brew Scale',
    description: 'Digital scale for precise pour-over brewing.',
    price: 34.99,
    currency: 'USD',
    status: 'draft',
    tags: ['equipment', 'brew', 'scale'],
    createdAt: '2026-02-03T15:45:00.000Z',
  },
  {
    id: 'prod-011',
    title: 'Filter Papers',
    description: 'Natural paper filters for pour-over drippers.',
    price: 7.25,
    currency: 'USD',
    status: 'active',
    tags: ['filters', 'brew', 'coffee'],
    createdAt: '2026-02-02T10:10:00.000Z',
  },
  {
    id: 'prod-012',
    title: 'Cold Foam Blender',
    description: 'Compact blender for preparing cold foam toppings.',
    price: 27.3,
    currency: 'USD',
    status: 'active',
    tags: ['equipment', 'foam', 'blender'],
    createdAt: '2026-02-01T13:20:00.000Z',
  },
];
